environment: staging
host: staging.example.com

application:
    sessionCookie: holizuki_staging_session
    cachePrefix: holizuki-staging-cache-

web:
    replicas: 1

database:
    name: holizuki_staging
    username: holizuki_staging

uploads:
    size: 10Gi

ingress:
    basicAuth:
        enabled: true
        secretName: holizuki-staging-basic-auth
    noIndex: true
