apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  labels:
    {{- include "holizuki-platform.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}-account-key
    server: {{ .Values.clusterIssuer.server }}
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
